### ISSUE TITLE
Make build_example lane optional

### ISSUE THREAD

**Issue by yoiang** [AFNetworking/fastlane#7]
Hey y'all! The fastlane scripts you've put together look awesome! 

For projects with no Example it would be great to the ability to choose not to attempt to build an Example project, currently not specifying one causes the scripts to fail.

Lemme know if this is in line with the project, if so I can try and make a PR!

**Comment by kcharwood** [comment]
Thanks @yoiang.

In that case, just use the `test_framework` lane directly. `ci_commit` was designed to roll both testing and building examples into one, but `test_framework` works fine for projects without an example. I'm doing there [here](https://github.com/AFNetworking/AFOAuth2Manager/blob/3_0_0_branch/.travis.yml#L8) for `AFOAuth2Manager`.

Would love your feedback. I'm still working out the kinks here!

**Comment by yoiang** [comment]
@kcharwood That worked great, thank you! 

Only issue I had after that was Travis skipped the deploy task because it didn't think it was a tagged commit (using fastlane prepare_framework_release version:0.5.6 --env deploy). I'll look into it more tomorrow and see if I can't suss it out but I noticed you had deploy disabled in AFOAuth2Manager, is it currently not functioning?

**Comment by kcharwood** [comment]
I'm still working on the deploy step for Travis. I haven't quite gotten it to work right for me with `AFNetworking`, and I haven't had time to circle back on it. I've been doing the `complete_framework_release` step manually from my own machine.

**Comment by yoiang** [comment]
Gotcha! Anyway I can help?

**Comment by kcharwood** [comment]
The thing I'm struggling with right now is how do I setup a build matrix (concurrent jobs that run different iOS versions/xcodes/etc), and if _all_ the jobs pass, how do I then run the deploy step. I haven't been able to thread that needle yet with Travis.

**Comment by kcharwood** [comment]
I've got a email going on with Travis. It looks like this isn't possible if you are using build matrices, but it sounds like they are working on something that may help me out.
